<?php

class CosmedicusMenu extends CBitrixComponent
{
    public function onPrepareComponentParams($arParams)
    {
        return parent::onPrepareComponentParams($arParams); // TODO: Change the autogenerated stub
    }

    public function executeComponent()
    {
        return parent::executeComponent(); // TODO: Change the autogenerated stub
    }
}